name: 'build-moonforge-action'
description: "Build moonforge images with kas"

inputs:
  kas_file:
    description: 'Path to the image kas file'
    required: true
  dl_dir:
    description: 'Path to the Yocto downloads directory'
    required: true
  sstate_dir:
    description: 'Path to the Yocto shared-state cache directory'
    required: true
  image_id:
    description: 'Image ID to be used in os-release'
    required: true
  image_version:
    description: 'Image version to be used in os-release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Clean previous builds
      shell: bash
      run: |
        rm -rf ./aux
        rm -rf ./build

    - name: Set kas environment variables
      env:
        DL_DIR: ${{ inputs.dl_dir }}
        SSTATE_DIR: ${{ inputs.sstate_dir }}
      shell: bash
      run: |
        if [ ! -d "${DL_DIR}" ]; then
          echo "${DL_DIR} directory does not exist"
          exit 1
        fi

        if [ ! -d "${SSTATE_DIR}" ]; then
          echo "${SSTATE_DIR} directory does not exist"
          exit 1
        fi

        echo "DL_DIR=${DL_DIR}" >> $GITHUB_ENV
        echo "SSTATE_DIR=${SSTATE_DIR}" >> $GITHUB_ENV
        echo "KAS_CONTAINER_ENGINE=docker" >> $GITHUB_ENV

    - name: Set image environment variables
      env:
        IMAGE_ID: ${{ inputs.image_id }}
        IMAGE_VERSION: ${{ inputs.image_version }}
      shell: bash
      run: |
          if [ -z "${IMAGE_ID}" ]; then
            echo "IMAGE_ID is empty"
            exit 1
          fi

          if [ -z "${IMAGE_VERSION}" ]; then
            echo "IMAGE_VERSION is empty"
            exit 1
          fi

          echo "IMAGE_ID=${IMAGE_ID}" >> $GITHUB_ENV
          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV

    - name: Set up auxiliary kas fragments
      shell: bash
      run: |
        mkdir -p ./aux
        cp ${GITHUB_ACTION_PATH}/kas/fetch.yml ./aux/fetch.yml
        cp ${GITHUB_ACTION_PATH}/kas/build.yml ./aux/build.yml

    - name: Fetch Yocto sources
      env:
        KAS_FILE: ${{ inputs.kas_file }}
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/scripts/kas-container \
          build \
          "${KAS_FILE}:./aux/fetch.yml" \
          -- --runonly=fetch

    - name: Build Yocto target
      env:
        KAS_FILE: ${{ inputs.kas_file }}
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/scripts/kas-container \
          --runtime-args "-e IMAGE_ID -e IMAGE_VERSION" \
          build \
          "${KAS_FILE}:./aux/build.yml"
